parameters:
- name: environment
  values:
  - "Preview"
  - "Production"

jobs:
- job: "Deploy"
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: "CloudflarePages"
  - name: "pnpm_config_cache"
    value: $(Pipeline.Workspace)/.pnpm-store
  steps:
  - checkout: none

  - task: PowerShell@2
    displayName: "Extract branch name"
    condition: and(succeeded(), eq(variables["Build.Reason"], "PullRequest"))
    name: "formatBranchName"
    inputs:
      targetType: "inline"
      script: |
        $sourceBranchName = "$(System.PullRequest.SourceBranch)"
        $sourceBranchName = $sourceBranchName.Replace("refs/heads/", "")
        Write-Host "##vso[task.setvariable variable=sourceBranchName;isOutput=true]$sourceBranchName"

  - download: current
    artifact: "dist"
    displayName: "Download build artifacts"

  - task: NodeTool@0
    displayName: "Install Node.js"
    inputs:
      versionSpec: "18.x"

  - task: PowerShell@2
    displayName: "Publish to Cloudflare Pages"
    name: "publishToCloudflarePages"
    inputs:
      targetType: "inline"
      script: |
        $output = npx wrangler pages deploy "../dist" --project-name "{{PROJECT-NAME}}" --branch $(formatBranchName.sourceBranchName)
        $output
        $cloudflareUrl = $output | Select-String -Pattern 'https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)' -AllMatches | ForEach-Object { $_.Matches } | ForEach-Object { $_.Value }
        Write-Host "##vso[task.setvariable variable=cloudflareUrl;isOutput=true]$cloudflareUrl"
    env:
      CLOUDFLARE_API_TOKEN: $(CLOUDFLARE_API_TOKEN)
      CLOUDFLARE_ACCOUNT_ID: $(CLOUDFLARE_ACCOUNT_ID)

  - task: PrMessenger@0
    displayName: "Set Comment on Pull Request"
    condition: and(succeeded(), eq(variables["Build.Reason"], "PullRequest"))
    inputs:
      messageSuccess: |
        # ✔ Build successful
        Website preview for branch `$(formatBranchName.sourceBranchName)` is available at [$(publishToCloudflarePages.cloudflareUrl)]($(publishToCloudflarePages.cloudflareUrl)).
        [🛠 Last build result]($( System.CollectionUri )$( System.TeamProject )/_build/results?buildId=$( Build.BuildId )&view=results)
      messageFailure: |
        # ❌ Build failed
        [🛠 Last build result]($( System.CollectionUri )$( System.TeamProject )/_build/results?buildId=$( Build.BuildId )&view=results)
      refreshMessagePosition: true
